This repo supports a static site for [[https://shawnhoover.dev][my personal links page]] and [[https://shawnhoover.dev/notes][Notes blog]].

- Content: a mix of static HTML and static image and style assets
- Blog generator: orgmode HTML publisher enhanced with [[file:publish/publish.el][various elisp functions]]
- Local preview: [[file:publish/server.rb][Ruby script]] supporting hot reloading
- Hosting: S3 and CloudFront
- Deployment: automated with GitHub Actions
- Site feed: yes, via the orgmode publish script

* Bootstrap
Requirements for the basic dev/writing setup:
- Emacs 28+ is required to build (and write with full orgmode capabilities,
  naturally)
- Ruby (recentish, e.g. ~3.0.2) is required to run the build server in writing
  mode with hot reloading

#+BEGIN_SRC sh
make build serve
open http://localhost:5000
#+END_SRC

* Orgmode-generated blog
The "Notes" blog is generated from .org files using the orgmode project
publishing system. Orgmode publishing generates styled HTML for all .org
files, as well as a sitemap. Internal .org file links are translated to
.html as expected. Generating an RSS feed requires somewhat more elbow
grease, but it's doable. See =Makefile= and =publish/publish.el= for
details.

* Build server and hot reloading
Running the build server (=publish/server.rb=) serves the local site in writing
mode. Upon saving any .org files in =notes/=, the server rebuilds the site and
notifies visiting browsers to reload the page.

* Infrastructure
The site is set up in AWS using the CloudFormation stacks in [[file:infra/][infra/]]. [[file:content/notes/static-site-aws-deployment.org][Deploying a
Static Site to AWS (in 2021-2023)]] discusses the setup.

Content is deployed via GitHub Actions, essentially:

#+BEGIN_SRC sh
pip install awscli # Or apt/brew install awscli
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
source infra/.env_deploy_main
make deploy
#+END_SRC
