#+title: "Expert Software Developers' Approach to Error" by Marian Petre
#+date: <2024-03-02 Sat 15:04>
#+setupfile: org.txt

#+BEGIN_QUOTE
Expert developers don't necessarily make less mistakes. They probably
make more. The difference is they have better safety nets.
#+END_QUOTE

--- [[https://youtu.be/UNMF5AS4SLg?si=_BZZO9dqoDfrgb2N][Marian Petre]] (as best I recall after listening to the talk)

I enjoyed this Strange Loop 2022 talk discussing many facets of the skills of
experts in high performing software teams and how they structure their work to
promote learning and share knowledge. Consistently delivering successful
outcomes in complex fields with resource constraints requires the application of
thought, effort, and creativity at every turn. This talk highlights great
examples of learning from errors, pair debugging, testing by breaking things,
triage by impact, and taking a break.

From now on, I will rationalize compromises left in the code as “works fine
within the Standard Operating Range” ;)

Stick around for the Q&A. I got a kick out of the speaker's story of being
brought in to conduct user interviews for a team that couldn't get approval to
do it with full time staff.
