# Builds the site and deploys to one of two sites depending on the branch being
# built. If triggered on main, deploy to the main www site. Otherwise deploy to
# stage-www.
#
# workflow_call is supported to the job reusable from email ingestion. In the
# call scenario, the `deploy_ref` input is required to select the branch to build.
#
# Ideally this would be factored into separate jobs: build, deploy stage, deploy
# www. Here, I inline for speed. I want the entire build to be done before I
# finish sipping my coffee.
name: Deployment
on:
  push:
    paths:
      - 'content/**'
      - 'publish/**'
  workflow_call:
    inputs:
      # Branch to build when reusing the workflow.
      deploy_ref:
        required: true
        type: string

env:
  # Override the time zone to the one that post timestamps were
  # written in. Orgmode assumes timestamps are in the default system
  # zone.
  TZ: EST+5EDT

  # The branch to deploy.
  DEPLOY_REF: ${{ inputs.deploy_ref || github.ref }}

jobs:
  deploy:
    name: Ship it!

    runs-on: ubuntu-latest
    permissions: # Needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.DEPLOY_REF }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::668334381016:role/shawnhoover-dev-ci-role
        aws-region: us-east-1

    # Emacs caching strategy:
    # - Emacs takes forever to build. Definitely don't do that.
    # - setup-emacs installs cleanly from the nix cache in about a minute. Nice,
    #   but too slow to use for every build.
    # - Use setup-emacs to install once (per version) and save to the GitHub
    #   cache. Cache the emacs package and all dependencies.
    # - On a cache hit, restore and link to /nix/store so dynamic linking works.
    # - Ideally, setup-emacs itself would save to the Action tool cache. That would require
    #   rewriting the Action in JS, I think.    
    - name: Cache emacs - Get
      id: cache-emacs
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/nix/store-emacs-29-1
        key: ${{ runner.os }}-emacs-29-1
   
    - name: Cache emacs - Hit
      if: steps.cache-emacs.outputs.cache-hit == 'true'
      run: |
        sudo mkdir -p /nix/store
        sudo ln -s $HOME/.local/nix/store-emacs-29-1/* /nix/store/
        emacs_store=$(find /nix/store -name "*-emacs-29-1")
        test -x $emacs_store/bin/emacs
        echo "$emacs_store/bin" >> $GITHUB_PATH

    - name: Cache emacs - Miss - Install
      uses: purcell/setup-emacs@master
      if: steps.cache-emacs.outputs.cache-hit != 'true'
      with:
        version: 29.1

    - name: Cache emacs - Miss - Put
      if: steps.cache-emacs.outputs.cache-hit != 'true'
      run: |
        ls -l `which emacs`
        emacs --version
        mkdir -p $HOME/.local/nix/store-emacs-29-1
        nix-store --query --requisites $(which emacs) | xargs -I {} rsync -av {} $HOME/.local/nix/store-emacs-29-1

    # Save 3s installing htmlize
    - name: Cache emacs packages
      uses: actions/cache@v3
      with:
        path: ~/.emacs.d/elpa
        key: emacs-packages-${{ hashFiles('script/setup-emacs.sh') }}

    - name: Build
      run: |
        set -x
        script/setup-emacs.sh
        make build
    - name: Deploy to AWS - stage
      if: env.DEPLOY_REF != 'refs/heads/main'
      run: |
        source infra/.env_deploy_stage
        make deploy

    - name: Deploy to AWS - main
      if: env.DEPLOY_REF == 'refs/heads/main'
      run: |
        source infra/.env_deploy_main
        make deploy

    # I don't look at the build unless there's a problem. Save the 3-7s upload
    # time otherwise.
    - name: Upload sitemap
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: sitemap
        path: notes/index.org

    - name: Upload build
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
