name: Trunk-based Deployment
on:
  push:

jobs:
  deploy-stage-www:
    name: Deploy stage-www

    runs-on: ubuntu-latest
    permissions: # Needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::668334381016:role/shawnhoover-dev-ci-role
        aws-region: us-east-1
    - uses: purcell/setup-emacs@master
      with:
        version: 29.1
    - name: Install Pandoc
      run: |
        wget -O $RUNNER_TEMP/pandoc.deb https://github.com/jgm/pandoc/releases/download/3.1.6.2/pandoc-3.1.6.2-1-amd64.deb
        sudo dpkg -i $RUNNER_TEMP/pandoc.deb
        pandoc --version

    - name: Build
      run: |
        make build

    - name: Deploy to AWS - stage
      run: |
        source .env_deploy_stage
        script/deploy-aws.sh

  deploy-www:
    name: Deploy www
    if: github.ref == 'refs/heads/main'
    needs: [deploy-stage-www]

    runs-on: ubuntu-latest
    permissions: # Needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::668334381016:role/shawnhoover-dev-ci-role
        aws-region: us-east-1

    - name: Deploy to AWS - main
      run: |
        source .env_deploy_main
        script/deploy-aws.sh
        
