name: Trunk-based Deployment
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: 29.1
    
    - run: |
        emacs --batch --directory publish --load publish/publish-org-dir.el pages

  deploy-to-stage:
    name: Deploy stage-www

    runs-on: ubuntu-latest
    permissions: # Needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::668334381016:role/shawnhoover-dev-ci-role
        aws-region: us-east-1

    - name: Deploy to AWS - stage
      run: |
        source .env_deploy_stage
        script/deploy-aws.sh

  deploy-to-main:
    name: Deploy www
    needs: [deploy-to-stage]
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    permissions: # Needed to interact with GitHub's OIDC Token endpoint.
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::668334381016:role/shawnhoover-dev-ci-role
        aws-region: us-east-1

    - name: Deploy to AWS - main
      run: |
        source .env_deploy_main
        script/deploy-aws.sh
        
